INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series
INSERT INTO series

INSERT INTO characters